[project]
authors = ["Ajay Arora <ajayarora1235@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Music-Source-Separation-Training"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.10.11"
pip = ">=25.1.1,<26"
[pypi-dependencies]
wxpython = "==4.2.0"
torch = ">=2.4.0, <2.5.0"
torchaudio = ">=2.4.0, <2.5.0"
numpy = "<2.0"
pandas = ">=2.3.0, <3"
scipy = ">=1.15.3, <2"
soundfile = ">=0.13.1, <0.14"
ml-collections = ">=1.1.0, <2"
tqdm = ">=4.67.1, <5"
segmentation-models-pytorch = "==0.3.3"
timm = "==0.9.2"
audiomentations = "==0.24.0"
pedalboard = ">=0.8.1"
omegaconf = "==2.2.3"
beartype = "==0.14.1"
rotary-embedding-torch = "==0.3.5"
einops = "==0.8.1"
librosa = ">=0.9.2, <0.10"
demucs = "==4.0.0"
transformers = "==4.35.2"
torchmetrics = "==0.11.4"
spafe = "==0.3.2"
protobuf = "==3.20.3"
torch-audiomentations = ">=0.12.0, <0.13"
asteroid = "==0.7.0"
auraloss = ">=0.4.0, <0.5"
torchseg = ">=0.0.1a1, <0.0.1a2"
bitsandbytes = ">=0.42.0, <0.43"
wandb = ">=0.20.1, <0.21"
accelerate = ">=1.7.0, <2"
huggingface-hub = ">=0.23.0"
prodigyopt = ">=1.1.2, <2"
torch-log-wmse = ">=0.3.0, <0.4"
loralib = ">=0.1.2, <0.2"
keyboard = ">=0.13.5, <0.14"
matplotlib = ">=3.10.3, <4"
sageattention = "==1.0.6"
pyaudio = ">=0.2.14, <0.3"
standard-aifc = ">=3.13.0, <4"
standard-sunau = ">=3.13.0, <4"
coremltools = "==8.3.0"
